### ISSUE TITLE
Expose nfc1-sys's `vendored` feature as a default feature

### ISSUE THREAD

**Issue by quad** [alexrsagen/rs-nfc1#6]
There's no way to disable the vendored libnfc when using the nfc1 crate.

**Comment by alexrsagen** [comment]
You should now be able to accomplish this in the following way:

```toml
[dependencies]
nfc1 = { version = "0.4", default-features = false }
```

Let me know if that works for you 🙂
